export const ActionTypes = {
  SET_BANNERS: "SET_BANNERS",
  GET_CATEGORYS: "GET_CATEGORYS",
  GET_HEADERS: " GET_HEADERS",
  GET_SELLINGPRODUCTS: "GET_SELLINGPRODUCTS",
  GET_NEWSLETTERS: "GET_NEWSLETTERS",
  GET_FOOTERS: "GET_FOOTERS",
  GET_PRODUCTBYID: "GET_PRODUCTBYID",
  GET_PRODUCTDETAILS: "GET_PRODUCTDETAILS",
  GET_CART: "GET_CART",
  GET_LOCATION: "GET_LOCATION",
  GET_PAYMENT: "GET_PAYMENT",
  GET_ORDERDATA: "GET_ORDERDATA",
};
